name: test
on:
  push:
    branches: ['main']
  pull_request:

jobs:
  test-ts:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout 🛒
        uses: actions/checkout@v6

      - name: checkout bmlt-query-client 🛒
        uses: actions/checkout@v6
        with:
          repository: bmlt-enabled/bmlt-query-client
          path: ../bmlt-query-client

      - name: node 24 ❇️
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: cache dependencies 💾
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: make npm ♦️
        run: |
          npm ci

      - name: make lint-js 🧹
        run: |
          npm run lint

      - name: make test-js 🧪
        run: |
          npm run coverage

      - name: upload coverage to Codecov 📊
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: codecov/codecov-action@v5
        with:
          files: coverage/cobertura-coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
